--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DanteDEVS/MurderMystery-LeyKey-Advance
build-by-default: true
branches:
- main
projects:
  MurderMystery-LeyKey-Advance:
    path: "" 
    icon: "icon.png"
...
