name: MurderMysteryAdvanceInfection
version: 1.0
api: [3.0.0]
author: LeyKey
main: mm\MurderMystery

commands:
  murdermystery:
    description: "Murder Mystery command"
    aliases: [mm, mrd]
