#
# MurderMystery plugin by LeyKey
#
# ========================
# Discord: LeyKey#0001
# Minecraft: LeyKeyy
# YouTube: LeyKey
# Edited: DanteDevs
# ========================
#
# {players} - Players in the game
# {innocents} - Innocents in the game
# {detec_status} - Status of the detective
# {role} - The players' role
# {map} - The map of the game
# {status} - Status of the game (Waiting for players / Starting in)
# {st} - Time until the game starts
# {gt} - Time until the games ends
# {rt} - Time until the game restarts when game is over
# \n - Line break
#
# Prefix
Prefix: §l§eMurderMystery§f:§r
#
# Speed of gold spawning (sec)
GoldSpawnRate: 3
#
# Gold spawns
GoldSpawns: 16
#
# Waiting status
WaitingStatus: §cWaiting for more players...
#
# Starting status
StartingStatus: §aStarting in {st}s
# if
# The scoreboard that gets displayed to players in the waiting lobby
LobbyScoreboard: 
- "§7§r"
- "§fPlayers: §a{players}/16"
- "§r§7"
- "§f{status}"
- "§b"
- "§fMap: §a{map}"
- "§b"
- "§eplay.yourserver.net"
#
# The scoreboard that gets displayed to players during a game
GameScoreboard:
- "§7§r"
- "§fRole: §a{role}"
- "§r"
- "§fInnocents left: §a{innocents}"
- "§fTime left: {gt}"
- "§a§r"
- "§fDetective: §a{detec_status}"
- "§r§7"
- "§fMap: §a{map}"
- "§b"
- "§eplay.yourserver.net"
#
# The scoreboard that gets displayed to players after a game
RestartScoreboard:
- "§7§r"
- "§fRole: §aDead"
- "§r"
- "§fInnocents left: §a0"
- "§fTime left: {rt}"
- "§a§r"
- "§fDetective: §a{detec_status}"
- "§r§7"
- "§fMap: §a{map}"
- "§b"
- "§eplay.yourserver.net"
